### ISSUE TITLE
cookie在github page中无效

### ISSUE THREAD

**Issue by Linkontoask** [radishes-music/radishes#15]
测试发现，无法在github page中发送带有cookie的http请求

表现为：登陆后会一直要求登录，并且每日推荐歌曲和歌单会出现问题

**Comment by little-buddy** [comment]
Maybe Ip + https that is invalid

![image](https://user-images.githubusercontent.com/30054881/102873870-a502f500-447c-11eb-8b79-ed2229b37b3a.png)

**Comment by Linkontoask** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/XMLHttpRequest/withCredentials
