### ISSUE TITLE
重构人员列表

### ISSUE THREAD

**Issue by Linkontoask** [radishes-music/radishes#6]
### 已参加人员与分工

+ [Link](https://github.com/Linkontoask) - 负责基本框架搭建
+ [little-buddy](https://github.com/little-buddy) - 负责登录

**Comment by little-buddy** [comment]
I want to join below:
    - login 
    - music control(part is also ok)
after finished, can do others.
    
😄😄😄

**Comment by Linkontoask** [comment]
Welcome to join in to complete the refactoring of the project @little-buddy

**Comment by little-buddy** [comment]
Hi Link:


&nbsp; &nbsp; 我看到你们有支持 electron 的更新，我这边是否也要做一些 electron 的调整?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Linkontoask/radishes"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月28日(星期一) 下午5:08
收件人:&nbsp;"Linkontoask/radishes"<radishes@noreply.github.com&gt;;
抄送:&nbsp;"仦瀦、兎吇"<aying.zhuai@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Linkontoask/radishes] 重构人员列表 (#6)





 
Welcome to join in to complete the refactoring of the project @little-buddy

**Comment by Linkontoask** [comment]
@little-buddy 暂时不需要，我们还在构思如何更好的支持各个平台

**Comment by Linkontoask** [comment]
@little-buddy Be aware of changes in responsibilities
