### ISSUE TITLE
客户端无法打开悬浮歌词

### ISSUE THREAD

**Issue by kelegele** [radishes-music/radishes#85]
**详细描述你的问题**

无法打开悬浮歌词
![image](https://github.com/radishes-music/radishes/assets/29626372/3b6f3218-7c06-4522-9cd0-9bfdc0136bdd)

**系统版本**
 - 客户端/网页端: win11 客户端
 - 客户端版本：2.0.0-alpha.5

**Comment by little-buddy** [comment]
这个问题已经修复了，只是没有发版 😊
